import { AssignmentType, WorkflowStage } from '@/types';

type StageTemplate = Omit<WorkflowStage, 'id' | 'assignedTo' | 'assignedToName' | 'dueDate' | 'status' | 'remarks' | 'attachmentLinks' | 'completedAt'>;

export const WORKFLOW_TEMPLATES: Record<AssignmentType, StageTemplate[]> = {
  conference_paper: [
    { name: 'Topic Finalization', order: 0 },
    { name: 'Literature Review', order: 1 },
    { name: 'Dataset Collection', order: 2 },
    { name: 'Methodology', order: 3 },
    { name: 'Writing', order: 4 },
    { name: 'Internal Review', order: 5 },
    { name: 'Plagiarism Check', order: 6 },
    { name: 'Formatting', order: 7 },
    { name: 'Submission', order: 8 },
    { name: 'Reviewer Comments', order: 9 },
    { name: 'Camera Ready Submission', order: 10 },
    { name: 'Presentation', order: 11 },
    { name: 'Published', order: 12 },
  ],
  journal_paper: [
    { name: 'Idea Generation', order: 0 },
    { name: 'Literature Review', order: 1 },
    { name: 'Experimentation', order: 2 },
    { name: 'Draft Writing', order: 3 },
    { name: 'Internal Review', order: 4 },
    { name: 'Journal Selection', order: 5 },
    { name: 'Submission', order: 6 },
    { name: 'Reviewer Review', order: 7 },
    { name: 'Revision', order: 8 },
    { name: 'Accepted', order: 9 },
    { name: 'Published', order: 10 },
  ],
  patent: [
    { name: 'Idea Generation', order: 0 },
    { name: 'Prior Art Search', order: 1 },
    { name: 'Drafting Claims', order: 2 },
    { name: 'Patent Drafting', order: 3 },
    { name: 'Internal Review', order: 4 },
    { name: 'Finalization', order: 5 },
    { name: 'Submission', order: 6 },
    { name: 'Examination', order: 7 },
    { name: 'Objection Handling', order: 8 },
    { name: 'Granted/Rejected', order: 9 },
  ],
  copyright: [
    { name: 'Content Preparation', order: 0 },
    { name: 'Verification', order: 1 },
    { name: 'Documentation', order: 2 },
    { name: 'Application Submission', order: 3 },
    { name: 'Review', order: 4 },
    { name: 'Approved/Rejected', order: 5 },
  ],
  research_proposal: [
    { name: 'Concept Development', order: 0 },
    { name: 'Literature Survey', order: 1 },
    { name: 'Objective Definition', order: 2 },
    { name: 'Methodology Design', order: 3 },
    { name: 'Budget Planning', order: 4 },
    { name: 'Draft Writing', order: 5 },
    { name: 'Internal Review', order: 6 },
    { name: 'Submission', order: 7 },
    { name: 'Evaluation', order: 8 },
    { name: 'Approved/Rejected', order: 9 },
  ],
  book_chapter: [
    { name: 'Topic Selection', order: 0 },
    { name: 'Outline Preparation', order: 1 },
    { name: 'Literature Review', order: 2 },
    { name: 'Draft Writing', order: 3 },
    { name: 'Internal Review', order: 4 },
    { name: 'Revision', order: 5 },
    { name: 'Formatting', order: 6 },
    { name: 'Submission', order: 7 },
    { name: 'Publisher Review', order: 8 },
    { name: 'Published', order: 9 },
  ],
  project: [
    { name: 'Requirement Analysis', order: 0 },
    { name: 'Planning', order: 1 },
    { name: 'Design', order: 2 },
    { name: 'Development', order: 3 },
    { name: 'Testing', order: 4 },
    { name: 'Review', order: 5 },
    { name: 'Deployment', order: 6 },
    { name: 'Completed', order: 7 },
  ],
  review_article: [
    { name: 'Topic Finalization', order: 0 },
    { name: 'Literature Collection', order: 1 },
    { name: 'Screening & Selection', order: 2 },
    { name: 'Data Extraction', order: 3 },
    { name: 'Analysis', order: 4 },
    { name: 'Writing', order: 5 },
    { name: 'Internal Review', order: 6 },
    { name: 'Submission', order: 7 },
    { name: 'Peer Review', order: 8 },
    { name: 'Published', order: 9 },
  ],
  survey_paper: [
    { name: 'Scope Definition', order: 0 },
    { name: 'Paper Collection', order: 1 },
    { name: 'Taxonomy Creation', order: 2 },
    { name: 'Analysis', order: 3 },
    { name: 'Writing', order: 4 },
    { name: 'Internal Review', order: 5 },
    { name: 'Submission', order: 6 },
    { name: 'Published', order: 7 },
  ],
  thesis_work: [
    { name: 'Topic Approval', order: 0 },
    { name: 'Literature Review', order: 1 },
    { name: 'Research Methodology', order: 2 },
    { name: 'Data Collection', order: 3 },
    { name: 'Analysis', order: 4 },
    { name: 'Thesis Writing', order: 5 },
    { name: 'Supervisor Review', order: 6 },
    { name: 'Revision', order: 7 },
    { name: 'Submission', order: 8 },
    { name: 'Viva/Defense', order: 9 },
    { name: 'Final Submission', order: 10 },
  ],
  other: [
    { name: 'Planning', order: 0 },
    { name: 'Execution', order: 1 },
    { name: 'Review', order: 2 },
    { name: 'Completion', order: 3 },
  ],
};

export const ASSIGNMENT_TYPE_LABELS: Record<AssignmentType, string> = {
  conference_paper: 'Conference Paper',
  journal_paper: 'Journal Paper',
  book_chapter: 'Book Chapter',
  patent: 'Patent',
  copyright: 'Copyright',
  research_proposal: 'Research Proposal',
  project: 'Project',
  review_article: 'Review Article',
  survey_paper: 'Survey Paper',
  thesis_work: 'Thesis Work',
  other: 'Other',
};

export const ASSIGNMENT_TYPE_COLORS: Record<AssignmentType, string> = {
  conference_paper: 'blue',
  journal_paper: 'violet',
  book_chapter: 'grape',
  patent: 'orange',
  copyright: 'teal',
  research_proposal: 'cyan',
  project: 'indigo',
  review_article: 'pink',
  survey_paper: 'lime',
  thesis_work: 'yellow',
  other: 'gray',
};

export const PRIORITY_COLORS = {
  critical: 'red',
  high: 'orange',
  medium: 'yellow',
  low: 'green',
} as const;

export const STAGE_STATUS_COLORS = {
  pending: 'gray',
  in_progress: 'blue',
  completed: 'green',
  review_required: 'yellow',
  rejected: 'red',
  accepted: 'teal',
} as const;

export const STAGE_STATUS_LABELS = {
  pending: 'Pending',
  in_progress: 'In Progress',
  completed: 'Completed',
  review_required: 'Review Required',
  rejected: 'Rejected',
  accepted: 'Accepted',
} as const;
